import type { Experience } from "./types";

export const experience: Experience[] = [
  {
    id: "dfc-software-engineer",
    company: "Dnyandeep Foundation Centre",
    companyUrl: "https://dfc.org.in/",
    role: "Software Engineer 1 (Mobile)",
    start: "Apr 2025",
    end: "Present",
    startStatus: "verified",
    endStatus: "verified",
    kind: "production-app",
    prominence: 1,
    summary:
      "Production ownership of DFC and AptiBooster, from feature work through Play Store release and maintenance.",
    highlights: [
      "Own and maintain two production Android apps: DFC and AptiBooster.",
      "Led the DFC mobile revamp on the existing Play listing — new TypeScript and TanStack Query codebase with onboarding, deep-link navigation, offline usage, and stronger auth/API error handling.",
      "Cut DFC p90 app start from ~894 ms to 794 ms on production Android with lazy-loaded navigators and startup-path refactors (~100 ms / 11.2% faster); ~5 MB lower JS heap at Home idle in internal profiling after the same work.",
      "Shipped a Firebase Crashlytics logger for fatal and non-fatal exceptions, with stack trace, API URL, and component context, plus selective axios interceptors that report actionable failures without flooding Crashlytics.",
      "Moved Zoom Meeting SDK out of DFC base delivery with an Android Dynamic Feature Module.",
      "Built AptiBooster so scoring, peer comparison, and analysis derive from one timed test attempt, and wired the mobile surfaces for API-backed insights, suggestions, and downloadable reports.",
    ],
    /** Shared + DFC + AptiBooster — priority order; home shows first 9 only. */
    technologies: [
      "React Native",
      "TypeScript",
      "Firebase",
      "Zoom Meeting SDK",
      "OneSignal",
      "Kotlin",
      "TanStack Query",
      "Razorpay React Native SDK",
      "Gifted Charts",
      "Microsoft Clarity",
      "Google Play In-App Updates",
      "Axios",
      "Context API",
    ],
    metricIds: ["dfc-app-start-p90"],
    projectIds: ["dfc-app", "aptibooster"],
  },
  {
    id: "dfc-intern",
    company: "Dnyandeep Foundation Centre",
    companyUrl: "https://dfc.org.in/",
    role: "Software Engineer Intern",
    start: "Dec 2024",
    end: "Mar 2025",
    startStatus: "verified",
    endStatus: "verified",
    kind: "internship",
    prominence: 4,
    summary:
      "Internship on the new DFC and AptiBooster apps—implemented most of the DFC mobile revamp in a fresh TypeScript repository (product flows, API layer, and screen work), with AptiBooster test and result analysis surfaces on the side.",
    highlights: [
      "Implemented the bulk of the new DFC app: replaced the legacy JavaScript codebase with TypeScript, TanStack Query, Axios (configured interceptors), and custom hooks so screens stay UI-focused and API logic stays separate.",
      "Shipped DFC onboarding with authentication and authorization API integration, additional DFC modules, and AptiBooster test and result analysis surfaces.",
    ],
    technologies: [
      "React Native",
      "TypeScript",
      "Firebase",
      "OneSignal",
      "TanStack Query",
      "MathJax",
      "Axios",
      "Context API",
    ],
    metricIds: [],
    projectIds: ["dfc-app", "aptibooster"],
    credentialUrl:
      "https://drive.google.com/file/d/1vN6y0zHncM9DwK6VtzDtDnYWNH-4SLvK/view?usp=sharing",
  },
  {
    id: "ikior-intern",
    company: "IKIOR",
    companyUrl: "https://www.ikior.com/",
    role: "Software Engineer Intern",
    start: "May 2023",
    end: "Nov 2023",
    startStatus: "verified",
    endStatus: "verified",
    kind: "internship",
    prominence: 4,
    summary:
      "Internship on IKIOR’s wellness mobile app—period tracking was the hero feature at the time. Built React Native UI from Figma, inspired by established period and health apps on the Play Store. The product has since been heavily revamped; today’s live app is not these internship surfaces.",
    highlights: [
      "Shipped period-tracking UI when it was the product hero—a cycle calendar with marked dates and per-day layouts built to surface insights as analysis was planned.",
      "Instagram Reels–inspired UI with react-native-video; multi-step period report flow; Health, Care, and Sleep section screens from Figma.",
    ],
    technologies: [
      "React Native",
      "JavaScript",
      "Redux Toolkit",
      "Context API",
      "React Native Video",
      "Figma",
    ],
    metricIds: [],
    projectIds: ["ikior"],
    credentialUrl:
      "https://drive.google.com/file/d/1d2kRf17t7UFew1xNG-MgxL9KyVSPA3sl/view?usp=sharing",
  },
];