import type { Experience } from "./types";

export const experience: Experience[] = [
  {
    id: "dfc-software-engineer",
    company: "Dnyandeep Foundation Centre",
    companyUrl: "https://dfc.org.in/",
    role: "Software Engineer 1 (Mobile)",
    start: "Apr 2025",
    end: "Present",
    startStatus: "verified",
    endStatus: "verified",
    kind: "production-app",
    prominence: 1,
    summary:
      "Production ownership of DFC and AptiBooster, from feature work through Play Store release and maintenance.",
    highlights: [
      "Own and maintain two production Android apps: DFC and AptiBooster.",
      "Led the DFC mobile revamp on the existing Play listing — new TypeScript and TanStack Query codebase with onboarding, deep-link navigation, offline usage, and stronger auth/API error handling.",
      "Cut DFC p90 app start from ~894 ms to ~794 ms on production Android with lazy-loaded navigators and startup-path refactors; ~5 MB lower JS heap at Home idle in internal profiling after the same work.",
      "Shipped a Firebase Crashlytics logger for fatal and non-fatal exceptions, with stack trace, API URL, and component context, plus selective axios interceptors that report actionable failures without flooding Crashlytics.",
      "Moved Zoom Meeting SDK out of DFC base delivery with an Android Dynamic Feature Module.",
      "Built AptiBooster so scoring, peer comparison, and analysis derive from one timed test attempt, and wired the mobile surfaces for API-backed insights, suggestions, and downloadable reports.",
    ],
    technologies: [
      "React Native",
      "TypeScript",
      "Kotlin",
      "TanStack Query",
      "Context API",
      "Firebase",
      "OneSignal",
      "Zoom Meeting SDK",
      "Android (native)",
    ],
    metricIds: ["dfc-app-start-p90"],
    projectIds: ["dfc-app", "aptibooster"],
  },
  {
    id: "dfc-intern",
    company: "Dnyandeep Foundation Centre",
    companyUrl: "https://dfc.org.in/",
    role: "Software Engineer Intern",
    start: "Dec 2024",
    end: "Mar 2025",
    startStatus: "verified",
    endStatus: "verified",
    kind: "internship",
    prominence: 4,
    summary:
      "Internship on the DFC and AptiBooster production apps—onboarding and auth/API integration on DFC, plus test and result analysis surfaces on AptiBooster.",
    highlights: [
      "Implemented AptiBooster test and result analysis surfaces.",
      "Implemented DFC onboarding UI with authentication and authorization API integration.",
    ],
    technologies: ["React Native", "React", "TypeScript"],
    metricIds: [],
    projectIds: ["dfc-app", "aptibooster"],
  },
  {
    id: "ikior-intern",
    company: "IKIOR",
    companyUrl: "https://www.ikior.com/",
    role: "Software Engineer Intern",
    start: "May 2023",
    end: "Nov 2023",
    startStatus: "verified",
    endStatus: "verified",
    kind: "internship",
    prominence: 4,
    summary:
      "Internship on IKIOR’s wellness mobile app—period tracking was the hero feature at the time. Built React Native UI from Figma, inspired by established period and health apps on the Play Store. The product has since been heavily revamped; today’s live app is not these internship surfaces.",
    highlights: [
      "Shipped period-tracking UI when it was the product hero—a cycle calendar with marked dates and per-day layouts built to surface insights as analysis was planned.",
      "Instagram Reels–inspired UI with react-native-video; multi-step period report flow; Health, Care, and Sleep section screens from Figma.",
      "Contributed to a 20–25% UI performance improvement on implemented screens.",
    ],
    technologies: [
      "React Native",
      "JavaScript",
      "Redux Toolkit",
      "Context API",
      "React Native Video",
      "Figma",
    ],
    metricIds: ["ikior-performance"],
    projectIds: ["ikior"],
  },
];